# Generated by Django 5.2.8 on 2025-11-11 16:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=10)),
                ('version', models.IntegerField(default=1)),
                ('content', models.TextField()),
            ],
            options={
                'unique_together': {('name', 'language', 'version')},
            },
        ),
    ]
