# Generated by Django 5.2.8 on 2025-11-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_content_template_body_text_template_body_html_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='body_html',
        ),
        migrations.RemoveField(
            model_name='template',
            name='body_text',
        ),
        migrations.AddField(
            model_name='template',
            name='body',
            field=models.JSONField(default=dict),
        ),
    ]
